language: node_js
node_js:
  - "stable"
script:
  - npm run build
notifications:
  email:
    recipients:
    - hengel2810@gmail.com
    on_success: always
    on_failure: always
before_deploy:
  - cd release-builds